### ISSUE TITLE
AttributeError: 'KEGGpathway' object has no attribute 'node'

### ISSUE THREAD

**Issue by kpj** [filippocastelli/KEGGutils#3]
Executing
```python
import KEGGutils as kg
pathway = kg.KEGGpathway(pathway_id='hsa05224')
```
yields the error `AttributeError: 'KEGGpathway' object has no attribute 'node'`.

This can be fixed by editing "KEGGutils/KEGGpathway.py":
```python
# line 164
self.pos.update({n: self.node[n]["xy"]})
# to
self.pos.update({n: self.nodes[n]["xy"]})

# line 484
"nodes": (self.node[e1]["name"], self.node[e2]["name"]),
# to
"nodes": (self.nodes[e1]["name"], self.nodes[e2]["name"]),
```

**Comment by filippocastelli** [comment]
@kpj thanks for the contribution! last commit should fix the issue

**Comment by kpj** [comment]
This is amazing, thank you so much!

**Comment by filippocastelli** [comment]
you're welcome, I'm happy to know this tool is useful for someone enough to open an issue.
have a nice day!
